version: '3'
services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      volumes:
         -/home/rocky/all-container-data/mariadb:/var/lib/mysql
    ports:
      - "3306:3306"
